export const PERMISSIONS = [
  "dashboard.read",
  "users.read",
  "users.write",
  "roles.read",
  "roles.write",
  "customers.read",
  "customers.write",
  "suppliers.read",
  "suppliers.write",
  "warehouses.read",
  "warehouses.write",
  "items.read",
  "items.write",
  "stock.read",
  "stock.transfer",
  "purchase_orders.read",
  "purchase_orders.write",
  "quotations.read",
  "quotations.write",
  "invoices.read",
  "invoices.write",
  "repairs.read",
  "repairs.write",
  "reports.read",
  "sales_orders.read",
  "sales_orders.write",
  "goods_receipts.read",
  "supplier_returns.read",
  "supplier_returns.write",
  "customer_returns.read",
  "customer_returns.write",
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];
